pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M2_HOME"
    }
    parameters {
        string(name: 'jobAndBranchName', defaultValue: 'Multiple Branch Pipeline/qa-1', description: 'Enter the input branch name')
    }
    environment {
        PATH = "C:\\Windows\\System32"
        JAVA_HOME = "C:\\Program Files\\Java\\jdk-21"
    }

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/Shiva1100/RestAssuredOne.git'
  script {
                    def jobName = env.JOB_NAME
                      def name = jobName.replaceAll(' ','_')
                    def branchName = name.takeAfterLast('/')
                    def jobAndBranchFormatedName = ${name}_${branchName}
                    
                    
                    echo "Job Name: ${jobName}"
                    def branchName = env.BRANCH_NAME
                    echo "branch Name: ${branchName}"
      echo "branch Name: ${jobAndBranchFormatedName}"
      
     }
                
            }

          
        }
         stage('Build') {
            steps {
                // Get some code from a GitHub repository
                dir('C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Multiple_Branch_Pipeline_master\\APITesting') {
                bat 'mvn clean package -Dmaven.compiler.source=8 -Dmaven.compiler.target=8 -Dmaven.test.failure.ignore=true'
                }
                
            }

          
        }
           stage('Test') {
            steps {
                  dir('C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Multiple_Branch_Pipeline_master\\APITesting') {
                bat 'mvn test'
                }
             
            }
        }
    }
      post {
              
                success{
                        echo "Ran successsfully"
                        emailext body: 'Build was Successful. No action Needed', subject: 'Reg Build confirmation from Jenkins', to: 'shiva509203@gmail.com'
                         archiveArtifacts 'APITesting/target/*.jar'
                }
            }
}
